name: tourism_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  country_picker: ^2.0.25

  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Eesti
      fonts:
        - asset: lib/assets/fonts/GT-Eesti-Bold.otf
        - asset: lib/assets/fonts/GT-Eesti-Light.otf
        - asset: lib/assets/fonts/GT-Eesti-Regular.otf
        - asset: lib/assets/fonts/GT-Eesti-Thin.otf

  # Add assets to your application
  assets:
    - lib/assets/images/Logo.png
    - lib/assets/images/facebook.png
    - lib/assets/images/google.png
    - lib/assets/images/phone.png
    - lib/assets/images/profile.png
    - lib/assets/images/background_budget.jpg
    
    


  # Uncomment and add custom fonts here if needed
  # To add assets to your application, add an assets section, like this:
  
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/place_images/AngKor_wat.jpg
    - lib/assets/place_images/AngKor.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
